In [1]:
import pandas as pd 
path = pd.read_csv('Downloads/train.csv')

In [2]:
df = pd.DataFrame(path)

In [31]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df.columns=df.columns.str.replace('-','_')

In [32]:
#Display the first 10 rows of the dataset.
df.head(10)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
5,6,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600
6,7,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520
8,9,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040
9,10,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000

In [33]:
#Find the total number of rows and columns.
df.shape

(9800, 18)

In [34]:
#Check the data types of all columns.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9800 non-null   int64
 1   order_id       9800 non-null   str
 2   order_date     9800 non-null   str
 3   ship_date      9800 non-null   str
 4   ship_mode      9800 non-null   str
 5   customer_id    9800 non-null   str
 6   customer_name  9800 non-null   str
 7   segment        9800 non-null   str
 8   country        9800 non-null   str
 9   city           9800 non-null   str
 10  state          9800 non-null   str
 11  postal_code    9789 non-null   float64
 12  region         9800 non-null   str
 13  product_id     9800 non-null   str
 14  category       9800 non-null   str
 15  sub_category   9800 non-null   str
 16  product_name   9800 non-null   str
 17  sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [38]:
#Display all unique values in the Category column.
df['category'].unique()

<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [39]:
#Find the number of unique customers.
len(df['customer_id'].unique())

793

In [40]:
#Count the number of orders in each Region.
df.groupby('region')['order_id'].count()

region
Central    2277
East       2785
South      1598
West       3140
Name: order_id, dtype: int64

In [41]:
#Find the total sales of the dataset.
print('$',df['sales'].sum())

$ 2261536.7827

In [42]:
#Find the maximum and minimum sales.
print('$',df['sales'].min())
print('$',df['sales'].max())

$ 0.444
$ 22638.48

In [43]:
#Display all orders from a specific city (e.g.Los Angeles).
df[df['city']=='Los Angeles']

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620
5,6,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860
6,7,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152
8,9,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9739,9740,CA-2018-129294,16/03/2018,21/03/2018,Standard Class,KD-16615,Ken Dana,Corporate,United States,Los Angeles,California,90032.0,West,OFF-BI-10001757,Office Supplies,Binders,Pressboard Hanging Data Binders for Unburst Sh...,19.680
9740,9741,CA-2018-129294,16/03/2018,21/03/2018,Standard Class,KD-16615,Ken Dana,Corporate,United States,Los Angeles,California,90032.0,West,OFF-AP-10001154,Office Supplies,Appliances,Bionaire Personal Warm Mist Humidifier/Vaporizer,140.670
9745,9746,CA-2018-137505,24/11/2018,24/11/2018,Same Day,BP-11290,Beth Paige,Consumer,United States,Los Angeles,California,90008.0,West,FUR-TA-10000617,Furniture,Tables,Hon Practical Foundations 30 x 60 Training Tab...,364.080
9746,9747,CA-2018-137505,24/11/2018,24/11/2018,Same Day,BP-11290,Beth Paige,Consumer,United States,Los Angeles,California,90008.0,West,FUR-TA-10001676,Furniture,Tables,Hon 61000 Series Interactive Training Tables,71.088
9764,9765,CA-2015-123855,18/06/2015,23/06/2015,Standard Class,MC-18100,Mick Crebagga,Consumer,United States,Los Angeles,California,90036.0,West,TEC-PH-10000215,Technology,Phones,Plantronics Cordless Phone Headset with In-lin...,139.800

In [44]:
df['city'].unique()

<StringArray>
[        'Henderson',       'Los Angeles',   'Fort Lauderdale',
           'Concord',           'Seattle',        'Fort Worth',
           'Madison',       'West Jordan',     'San Francisco',
           'Fremont',
 ...
        'Pine Bluff',          'Aberdeen',        'Hagerstown',
       'East Orange', 'Arlington Heights',            'Oswego',
       'Coon Rapids',      'San Clemente',   'San Luis Obispo',
        'Springdale']
Length: 529, dtype: str

In [45]:
#Find all products belonging to the Technology category.

df[df['category']=='Technology']

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152
11,12,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.424
19,20,CA-2015-143336,27/08/2015,01/09/2015,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109.0,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480
26,27,CA-2017-121755,16/01/2017,20/01/2017,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,California,90049.0,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570
35,36,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9780,9781,CA-2017-153178,14/09/2017,18/09/2017,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Long Beach,New York,11561.0,East,TEC-PH-10001944,Technology,Phones,Wi-Ex zBoost YX540 Cellular Phone Signal Booster,437.850
9789,9790,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,TEC-AC-10004901,Technology,Accessories,Kensington SlimBlade Notebook Wireless Mouse w...,39.992
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [46]:
#Find the average sales by Sub-Category.
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales'],
      dtype='str')

In [47]:
#Find the total sales for each Region and Category.
round(df.groupby(['region','category'])['sales'].sum(),2)

region   category
Central  Furniture          160317.46
         Office Supplies    163590.24
         Technology         168739.21
East     Furniture          206461.39
         Office Supplies    199940.81
         Technology         263116.53
South    Furniture          116531.48
         Office Supplies    124424.77
         Technology         148195.21
West     Furniture          245348.25
         Office Supplies    217466.51
         Technology         247404.93
Name: sales, dtype: float64

In [48]:
#Find the highest sale in each Sub-Category.
df.groupby('sub_category')['sales'].max()

sub_category
Accessories     3347.370
Appliances      2625.120
Art             1113.024
Binders         9892.740
Bookcases       4404.900
Chairs          4416.174
Copiers        17499.950
Envelopes        604.656
Fasteners         93.360
Furnishings     1336.440
Labels           786.480
Machines       22638.480
Paper            733.950
Phones          4548.810
Storage         2934.330
Supplies        8187.650
Tables          4297.644
Name: sales, dtype: float64

In [49]:
#Find the lowest sale in each State.
df.groupby('state')['sales'].min()

state
Alabama                    3.620
Arizona                    1.408
Arkansas                   4.300
California                 0.990
Colorado                   1.080
Connecticut                3.520
Delaware                   3.380
District of Columbia       9.640
Florida                    1.167
Georgia                    1.780
Idaho                      3.304
Illinois                   0.836
Indiana                    1.980
Iowa                       5.400
Kansas                     5.760
Kentucky                   2.610
Louisiana                  3.890
Maine                      8.260
Maryland                   1.640
Massachusetts              3.150
Michigan                   2.200
Minnesota                  3.750
Mississippi                6.160
Missouri                   7.640
Montana                    6.096
Nebraska                   5.040
Nevada                     3.640
New Hampshire             14.820
New Jersey                 3.760
New Mexico                 4.170
New York                   1.240
North Carolina             1.752
North Dakota               2.480
Ohio                       1.448
Oklahoma                   3.520
Oregon                     1.080
Pennsylvania               0.852
Rhode Island               2.220
South Carolina             6.460
South Dakota               2.970
Tennessee                  1.584
Texas                      0.444
Utah                       4.960
Vermont                    2.040
Virginia                   2.840
Washington                 1.344
West Virginia              6.240
Wisconsin                  1.810
Wyoming                 1603.136
Name: sales, dtype: float64

In [50]:
#Find the top-selling product in each category.
df.groupby(['category','product_name'])['sales'].max()

category    product_name
Furniture   12-1/2 Diameter Round Wall Clock                                                                       199.800
            24-Hour Round Wall Clock                                                                               159.840
            36X48 HARDFLOOR CHAIRMAT                                                                               167.840
            3M Hangers With Command Adhesive                                                                        23.680
            3M Polarizing Light Filter Sleeves                                                                     111.900
                                                                                                                    ...
Technology  iKross Bluetooth Portable Keyboard + Cell Phone Stand Holder + Brush for Apple iPhone 5S 5C 5, 4S 4    209.500
            iOttie HLCRIO102 Car Mount                                                                             119.940
            iOttie XL Car Mount                                                                                    143.928
            invisibleSHIELD by ZAGG Smudge-Free Screen Protector                                                    89.950
            netTALK DUO VoIP Telephone Service                                                                     377.928
Name: sales, Length: 1849, dtype: float64

In [51]:
# Find the number of unique customers in each region.
df.groupby('region')['customer_id'].nunique()

region
Central    626
East       669
South      509
West       681
Name: customer_id, dtype: int64

In [52]:
# Find the city having the highest average sales.
a= df.groupby('city')['sales'].mean()

for city, price in a.items():
    if price == a.max():
        print(f"City name {city} Average maximun value is {price}")

City name Jamestown Average maximun value is 2354.395

In [53]:
# Find the category contributing the highest percentage of total sales.

m = df.groupby('category')['sales'].sum() / df['sales'].sum()*100
# for c, i in m.items():
#     if i == m.max():
#         print(c, i )


print(m.idxmax(), m.max())

Technology 36.58821202156696

In [56]:
# Find the category contributing the highest percentage of total sales.
df.groupby('category')['sales'].sum()/df['sales'].sum()*100

category
Furniture          32.219621
Office Supplies    31.192167
Technology         36.588212
Name: sales, dtype: float64

In [77]:
# Find states where total sales exceed 50,000.
state_total= df.groupby('state')['sales'].sum()
state_total[state_total>50000]

state
California        446306.4635
Florida            88436.5320
Illinois           79236.5170
Michigan           76136.0740
New York          306361.1470
North Carolina     55165.9640
Ohio               75130.3500
Pennsylvania      116276.6500
Texas             168572.5322
Virginia           70636.7200
Washington        135206.8500
Name: sales, dtype: float64

In [99]:
# Find the top customer from each region based on sales.
group_region= df.groupby(['region','customer_name'])['sales'].sum().reset_index()
top_cus= group_region.loc[group_region.groupby('region')['sales'].idxmax()]

top_cus

       region customer_name      sales
576   Central  Tamara Chand  18437.138
1268     East  Tom Ashbrook  13723.498
1734    South   Sean Miller  23669.196
2340     West  Raymond Buch  14345.276

In [109]:
# Find the top customer from each region based on sales.
reg= df.groupby(['region','customer_name'])['sales'].sum().reset_index()

reg['rank']=reg.groupby('region')['sales'].rank(method='dense',ascending=False)
reg[reg['rank']==1]

       region customer_name      sales  rank
576   Central  Tamara Chand  18437.138   1.0
1268     East  Tom Ashbrook  13723.498   1.0
1734    South   Sean Miller  23669.196   1.0
2340     West  Raymond Buch  14345.276   1.0

In [118]:
# Convert Order Date to datetime.
df['order_date']=pd.to_datetime(df['order_date'])

In [150]:
# Extract year, month, and day from Order Date.
print(pd.concat([
    df['order_date'].dt.year.rename('Year'),
    df['order_date'].dt.month.rename('Month'),
    df['order_date'].dt.day.rename('day')
    
],axis=1))

      Year  Month  day
0     2017     11    8
1     2017     11    8
2     2017      6   12
3     2016     10   11
4     2016     10   11
...    ...    ...  ...
9795  2017      5   21
9796  2016      1   12
9797  2016      1   12
9798  2016      1   12
9799  2016      1   12

[9800 rows x 3 columns]

In [154]:
# Find total sales for each year.

order_date
2015    479856.2081
2016    459436.0054
2017    600192.5500
2018    722052.0192
Name: sales, dtype: float64

In [160]:
# Find total sales for each month.
months = df['order_date'].dt.month.rename('Month')
df.groupby(months)['sales'].sum()

Month
1      94291.6296
2      59371.1154
3     197573.5872
4     136283.0006
5     154086.7237
6     145837.5233
7     145535.6890
8     157315.9270
9     300103.4117
10    199496.2947
11    350161.7110
12    321480.1695
Name: sales, dtype: float64

In [165]:
import os
os.getcwd()

'C:\\Users\\dheer'